server {
    server_name glomespace.com;


    location / {
        root /var/www/app;
        try_files $uri $uri/ /index.html;
    }

    # Proxy /api/* → website-api.glomespace.com
    location /api/ {
        proxy_pass https://website-api.glomespace.com/;
        proxy_set_header Host api.glomespace.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Critical: forward cookies both ways
        proxy_pass_request_headers on;
        proxy_cookie_domain website-api.glomespace.com glomespace.com;
        proxy_cookie_path / /;
    }
}